# Generated by Django 4.0.5 on 2022-07-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tilte_blogpost_title_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='tilte',
        ),
    ]
